[project]
name = "Tobit Trend Analysis"
version = "0.1.0"

[global_settings]
run_ver = "v6_042026"
output_dir = "outputs"

[calculate_distance] # script00 - CALCULATE DISTANCE
well_info_well = "input/00_Data/WELL.csv"
gauge_locs = "input/00_Data/Trend_Analysis_Data/RiverGageLocations-2-21-2020.csv"
river_shapefile = "input/00_Data/Trend_Analysis_Data/rivKrigeHigh.shp"

[prep_chem] # script01 - PREP CHEMISTRY DATA
#script01 - PREP CHEMISTRY DATA
chemistry_files = [
  "input/00_Data/Chemistry_Data/CY24/qry_GW_REPORT_CY2024_GWSR_1.txt",
  "input/00_Data/Chemistry_Data/CY24/qry_GW_REPORT_CY2024_GWSR_2.txt",
  "input/00_Data/Chemistry_Data/CY24/qry_GW_REPORT_CY2024_GWSR_3.txt"
]
river_stage_file = "input/00_Data/STAGE_COMB.csv"
well_info_screen = "input/00_Data/SCREEN.csv"
##############
# pre-processing of chem db - no analyte filtering here!!
analytes = [Chromium, Hexavalent Chromium]
chromium_analyte = "Chromium"  #analyte to filter chem database for
hexchrom_analyte = "Hexavalent Chromium" 
filtered_keep_value = "Y"
combined_analyte_name = "Hex. Chromium and Fil. Chromium"
############
## WELL FILTERING 
filter_columns = [STATUS,OU]
filter_c1 = ["DECOMMISSIONED-V", "DRILLING CANCELLED"]
filter_c2 = ["100-KR-4", "100-HR-3-D", "100-HR-3-H"]

status_exclude = ["DECOMMISSIONED-V", "DRILLING CANCELLED"] # Well statuses to exclude col: STATUS
status_exclude_col = "STATUS"
ou_keep = ["100-KR-4", "100-HR-3-D", "100-HR-3-H"] # List of OUs to keep col: OU
ou_keep_col = "OU"
## CHEM FILTERING
MDL_VALUE = 1 #???
mdl_sub_if_nonpositive_missing = 1.0 #fill MDL when VAL <= 0 and MDL is missing - non-detect handling
reviewq_remove_patterns = ["Y", "R"] # Patterns searched in REVIEWQ; matching rows are removed
collection_purpose_exclude = ["IH", "C", "VAR", "VP", "RC", "WM", "S", "PE", "T", "PD", "CNF"] # list of COLLECTION_PURPOSE codes to remove
duplicate_handling = "daily_avg"
trend_min_year = 2008 # Minimum year threshold for including a well in the trend dataset - USE FULL DATE!!!
CHEM_YEAR = 2024 # Max chemistry analysis year cutoff - USE FULL DATE!!!

[prep_wl] # script02 - PREP WATER LEVEL DATA
wl_file = "input/00_Data/01_combined_hourly_AWLN_HEIS_CY06_24_v1_031225.csv"
WL_YEAR = 2024  # water level analysis year cutoff - USE FULL DATE!!!

[wl_trends] # script03
mindate = "1994-01-01"

[tobit_trends] # script04 - CHEMISTRY TOBIT TREND ANALYSIS
system_wells_csv = "input/SystemWells.csv"
trend_breaks_csv = "input/TrendBreaks_v051824.csv"
no_rs_csv = "input/NoRS.csv"
kw_csv = "input/KW_selected_locations.csv"
rum_csv = "input/list_RUM2_wells_and_beyond_v4_021225.csv"
r_script_path = "src/tools/crosscor_r_bridge.R"

[model]
dep = "VAL" # dependent variable
indep = ["INTERP", "EVENT"] 
log = "log"
maxlag = 90
n_min = 7
pnd_max = 0.5


[data_rules]
PRIOR_YEAR = 2023

[CUTOFFS]
DX = "2011-01-01"
HX = "2011-11-01"
KX_KW_KR4 = "2009-04-01"

[KW_DATES]
date1 = "2016-05-16"
date2 = "2017-04-12"


[run] # TBC 
save_csv = true
save_plots = true
save_diagnostics = true
compare_to_r = true
